/**
 * deploy-local.ts
 * Deploys contracts to the local Hardhat node, mints test cUSD to the
 * first 5 accounts, and writes a ready-to-use frontend/.env.local file.
 *
 * Usage:
 *   # Terminal 1 — start local node
 *   npx hardhat node
 *
 *   # Terminal 2 — deploy + setup
 *   npx hardhat run scripts/deploy-local.ts --network localhost
 *
 *   # Terminal 3 — start frontend
 *   cd ../frontend && npm run dev
 */

import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const signers = await ethers.getSigners();
  const [deployer, treasury, oracleHotWallet, alice, bob, carol] = signers;

  console.log("\n=== Celo Grind — Local Dev Deployment ===");
  console.log(`Network:  ${network.name} (chainId: 31337)`);
  console.log(`Deployer: ${deployer.address}`);

  // ── 1. Deploy MockERC20 as local "cUSD" ──────────────────────────────────

  console.log("\n[1/4] Deploying MockUSDT (local testnet token)...");
  const MockERC20 = await ethers.getContractFactory("MockERC20");
  const usdt = await MockERC20.deploy("Tether USD", "USDT", 6);
  await usdt.waitForDeployment();
  const usdtAddress = await usdt.getAddress();
  console.log(`      MockUSDT: ${usdtAddress}`);

  // Mint 10,000 USDT to the first 6 accounts for testing
  const mintAmount = ethers.parseUnits("10000", 6);
  for (const signer of [deployer, alice, bob, carol, treasury]) {
    await usdt.mint(signer.address, mintAmount);
    console.log(`      Minted 10,000 USDT → ${signer.address}`);
  }

  // ── 2. Deploy CeloGrindVault ──────────────────────────────────────────────

  console.log("\n[2/4] Deploying CeloGrindVault...");
  const Vault = await ethers.getContractFactory("CeloGrindVault");
  const vault = await Vault.deploy(usdtAddress, treasury.address);
  await vault.waitForDeployment();
  const vaultAddress = await vault.getAddress();
  console.log(`      CeloGrindVault: ${vaultAddress}`);

  // ── 3. Deploy StreakOracle ────────────────────────────────────────────────

  console.log("\n[3/4] Deploying StreakOracle...");
  const Oracle = await ethers.getContractFactory("StreakOracle");
  const oracle = await Oracle.deploy(vaultAddress, oracleHotWallet.address);
  await oracle.waitForDeployment();
  const oracleAddress = await oracle.getAddress();
  console.log(`      StreakOracle: ${oracleAddress}`);

  // Grant ORACLE_ROLE to StreakOracle on vault
  const ORACLE_ROLE = await vault.ORACLE_ROLE();
  await vault.grantRole(ORACLE_ROLE, oracleAddress);

  // Grant KEEPER_ROLE to deployer for manual round resolution during testing
  const KEEPER_ROLE = await vault.KEEPER_ROLE();
  await vault.grantRole(KEEPER_ROLE, deployer.address);
  console.log(`      Roles configured.`);

  // ── 4. Write frontend/.env.local ─────────────────────────────────────────

  console.log("\n[4/4] Writing frontend/.env.local...");
  const envContent = `# Auto-generated by deploy-local.ts — DO NOT COMMIT
# Regenerate by running: npx hardhat run scripts/deploy-local.ts --network localhost

NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_CELO_RPC_URL=http://127.0.0.1:8545

NEXT_PUBLIC_VAULT_ADDRESS=${vaultAddress}
NEXT_PUBLIC_ORACLE_ADDRESS=${oracleAddress}
NEXT_PUBLIC_USDT_ADDRESS=${usdtAddress}

# Charity address for TxShortcut — use account 3 locally (carol)
NEXT_PUBLIC_CHARITY_ADDRESS=${carol.address}

# No Graph in local dev — frontend will fall back to contract reads
NEXT_PUBLIC_GRAPH_API_URL=
`;

  const envPath = path.join(__dirname, "../../frontend/.env.local");
  fs.writeFileSync(envPath, envContent);
  console.log(`      Written to: ${envPath}`);

  // ── Summary ───────────────────────────────────────────────────────────────

  console.log("\n=== Local Dev Setup Complete ===");
  console.log("\nTest accounts (all pre-funded with 10,000 USDT + ETH for gas):");
  console.log(`  Deployer/Admin : ${deployer.address}`);
  console.log(`  Treasury       : ${treasury.address}`);
  console.log(`  Oracle HotWallet: ${oracleHotWallet.address}`);
  console.log(`  Alice          : ${alice.address}`);
  console.log(`  Bob            : ${bob.address}`);
  console.log(`  Carol          : ${carol.address}`);
  console.log("\nContracts:");
  console.log(`  MockUSDT       : ${usdtAddress}`);
  console.log(`  CeloGrindVault : ${vaultAddress}`);
  console.log(`  StreakOracle   : ${oracleAddress}`);
  console.log("\nNext steps:");
  console.log("  1. Add localhost to MetaMask: http://127.0.0.1:8545, chainId 31337");
  console.log("  2. Import a test account private key into MetaMask (see Hardhat node output)");
  console.log("  3. cd ../frontend && npm run dev");
  console.log("  4. Open http://localhost:3000");
  console.log("\nHardhat node private keys (first 3):");
  console.log("  Account #0: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80");
  console.log("  Account #1: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d");
  console.log("  Account #2: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a");
  console.log("  Account #3: 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
